---
- name: wait for file spbtest
  hosts: s01ttapaap
  strategy: debug
  become_user: bs_pa2000
  become_method: sudo
- wait_for:
    path: /tmp/spbtest.txt
    delay: 10
    sleep: 60
    search_regex: "spb war da"
    
