- name: Hello World Sample
  hosts: s01ttapaap
  become_user: bs_pa2000

  tasks:
    - name: Hello WhoAmI
      shell:
        cmd: "whoami"
      register: out
      environment:
        HOSTNAME: "s01ttapaap"
    - debug: msg={{ out.stdout }} 

