---

- name: test_parallel  
  hosts: all
  strategy: free
  become_user: bs_pa2000
  become_method: sudo
  vars:
    data_path: /app/DANTE/data/pa2000
    jk_path: /app/DANTE/work/data/jk/pa2000
    cob_path: /app/DANTE/exec/bin/cob
       
  - name: Hello WhoAmI
    shell:
        cmd: "sleep 5"
    register: out
  - debug: msg={{ out.stdout }} 
