- name: Hello World Sample
  hosts: all
  become_user: bs_pa2000
  become_method: sudo
  vars:
    data_path: /app/DANTE/data/pa2000
  tasks:
    - name: Hello WhoAmI
      shell:
        cmd: "whoami"
      register: out
#      environment:
#        DD_ANWKONTB: "{{ data_path }}/DAT.ANWKONT.PAANX200"
#        DD_ANWKONTG: "{{ data_path }}/fksjflksjf"      
    - debug: msg:{{ out.stdout }}
    
    - name: Hello sudo
      shell:
        cmd: "sudo -l"
      register: out2
    - debug: msg:{{ out2.stdout }}

