- name: Hello World Sample
  hosts: all
  tasks:
    - name: Hello WhoAmI
      shell:
        cmd: "whoami"
      register: out
    - debug: msg={{ out.stdout }}
    
    - name: Hello sudo
      shell:
        cmd: "sudo -l"
      register: out2
    - debug: msg={{ out2.stdout }}

