---

- name: multi_deploy_test  
  hosts: s01ttwaslb1
  #hosts: s01ttapaap
  strategy: debug
  become_user: wasadmin
  become_method: sudo
  #become_user: bs_pa2000
  #become_method: sudo
  
  vars:
    stage: s01ttwaslb1
    #was_port: 8879
    was_cluster: "WAS_Cluster01"
    was_user: wasadmin
    was_password: "8hebngrwie!"
    was_temp: "/tmp"
    py_temp: "/tmp/deploy.py"
    was_war: fahrradpass-war-4.0.0.war
    mytext: |
      import sys, string
      def rf_trim_comma(str):
          if str[:1] == ',':
            str = str[1:len(str)]
          
          if str[len(str)-1:] == ',':
            str = str[:len(str)-1]
          return str
          
      def rf_prep_str(val):
          if val == None:
              return None
          
          i = len(val)
          if i == 0:
              return None
              
          retval = val.strip()
          retval = rf_trim_comma(retval)
          
          j = len(retval)
          
          if i != j:
              retval = rf_prep_str(retval)          
          return retval
          
    
    
         
  tasks: 
  - name: create python script
    copy:
      dest: "{{ py_temp }}"
      content: "{{ mytext }}"
    
