---

- name: multi_deploy_test  
  hosts: s01ttwaslb1
  strategy: debug
  become_user: wasadmin
  become_method: sudo
  vars:
    stage: s01ttwaslb1
    port: 8879
    was_cluster: "WAS_Cluster01"
    was_user: wasadmin
    was_password: "8hebngrwie!"
    was_temp: /tmp/
    was_war: fahrradpass-war-4.0.0.war

  - name: create python script
    file:
      path: "{{ was_temp }}/deploy.py"
      state: touch
      content: | 
        Hallihallo 

        
  - name: Hello WhoAmI
    shell:
        cmd: "whoami"
    register: out
  - debug: msg={{ out.stdout }}      
  
  #- name: exports for program paanwkon
  #  command: "{{ cob_path }}/paanwkon"
 #   #command: "/app/hsthome/02ud190j/spbtest2"
  #  register: anwkon
 #   environment: 
   #   DD_ANWKONTB: "{{ data_path }}/DAT.ANWKONT.PAANX200"      
  #- debug:
  #    msg: "{{ anwkon }}"
   #   verbosity: 4
      
  #- name: Cat Output
  #  shell: cat {{ data_path }}/SYSLST.PAANWKON       
  #  register: out
 # - debug: msg={{ out.stdout }}   
