---
- name: paanwkon_test
  hosts: s01ttapaap
  become_user: bs_pa2000
  become_method: sudo
  vars:
    data_path: /app/DANTE/data/pa2000
    jk_path: /app/DANTE/work/data/jk/pa2000
    cob_path: /app/DANTE/exec/bin/cob
    

  tasks:
  - name: clear files
    file:
      path: "{{ data_path }}/temp1"
      state: absent

  - name: clear DAT.ANWKONT.DZ
    file:
      path: "{{ data_path }}/DAT.ANWKONT.DZ"
      state: absent

  - name: check if D.FEHLER is present
    stat:
      path: "{{ data_path }}/D.FEHLER"
    register: ff

  - name: write to variable if file exists
    stat:
      path: "{{ item }}" 
    loop:
      - "{{ data_path }}/DAT.ANWKONT.PAANX200"
      - "{{ data_path }}/DAT.ANWKONT.PAANX300"
      - "{{ data_path }}/DAT.ANWKONT.PAANX400"
      - "{{ data_path }}/PASTLN02.VGLANW.210716.1"
    register: out    
    
 # - name: fails if D.ANWKONT Files are not present
 #   fail:
 #     msg: "{{ data_path }}/DAT.ANWKONT do not exist"
 #   when: out.stat.exists == false

  - name: create jk file and content
    file:
      path: "{{ jk_path }}/JK.PAANWKON"
      state: touch
      content: | 
        OK;;;
  - name: exports for program paanwkon
    shell:
      cmd: "{{ cob_path }}/paanwkon"
    environment:
      DD_ANWKONTB: "{{ data_path }}/DAT.AWNKONT.PAANX200"
      DD_ANWKONTG: "{{ data_path }}/DAT.ANWKONT.PAANX300"
      DD_ANWKONTA: "{{ data_path }}/DAT.AWNKONT.PAANX400"
      DD_ANWPASTL: "{{ data_path }}/PASTLN02.VGLANW.210716.1"
      DD_FEHLER: "{{ data_path }}/D.FEHLER"
      DD_ANWRZDZ: "{{ data_path }}/DAT.ANWKONT.DZ"
      DD_HREZDZ: "{{ data_path }}/DAT.ANWKONT.HREZDZ.xml"
      DD_JKFILE: "{{ jk_path }}/app/DANTE/work/data/jk/pa2000/JK.PAANWKON"
    register: anwkon
  - debug: msg={{ anwkon.stdout }}
  - debug:
      var: anwkon
  - debug: msg="Fehler File exists"
    when: ff.stat.exists
