---

- name: paanwkon_test  
  hosts: s01ttapaap
  become_user: bs_pa2000
  become_method: sudo
  vars:
    data_path: /app/DANTE/data/pa2000
    jk_path: /app/DANTE/work/data/jk/pa2000
    cob_path: /app/DANTE/exec/bin/cob
    

  tasks:
  - name: clear files
    file:
      path: "{{ data_path }}/temp1"
      state: absent

  - name: clear DAT.ANWKONT.DZ
    file:
      path: "{{ data_path }}/DAT.ANWKONT.DZ"
      state: absent

  - name: check if D.FEHLER is present
    stat:
      path: "{{ data_path }}/D.FEHLER"
    register: ff

  - name: write to variable if file exists
    stat:
      path: "{{ item }}" 
    loop:
      - "{{ data_path }}/DAT.ANWKONT.PAANX200"
      - "{{ data_path }}/DAT.ANWKONT.PAANX300"
      - "{{ data_path }}/DAT.ANWKONT.PAANX400"
      - "{{ data_path }}/PASTLN02.VGLANW.210716.1"
    register: out    
    
 # - name: fails if D.ANWKONT Files are not present
 #   fail:
 #     msg: "{{ data_path }}/DAT.ANWKONT do not exist"
 #   when: out.stat.exists == false

  - name: create jk file and content
    file:
      path: "{{ jk_path }}/JK.PAANWKON"
      state: touch
      content: | 
        OK;;;
        
  - name: Hello WhoAmI
    shell:
        cmd: "whoami"
    register: out
  - debug: msg={{ out.stdout }}      
  
  - name: exports for program paanwkon
    command: "{{ cob_path }}/paanwkon"
    register: anwkon
    environment:
      DD_ANWKONTB: "{{ data_path }}/DAT.ANWKONT.PAANX200"
      DD_ANWKONTG: "{{ data_path }}/DAT.ANWKONT.PAANX300"
      DD_ANWKONTA: "{{ data_path }}/DAT.ANWKONT.PAANX400"
      DD_ANWPASTL: "{{ data_path }}/PASTLN02.VGLANW.210716.1"
      DD_FEHLER: "{{ data_path }}/D.FEHLER"
      DD_ANWRZDZ: "{{ data_path }}/DAT.ANWKONT.DZ"
      DD_HREZDZ: "{{ data_path }}/DAT.ANWKONT.HREZDZ.xml"
      DD_JKFILE: "{{ jk_path }}/app/DANTE/work/data/jk/pa2000/JK.PAANWKON"
      HOSTNAME: "$(hostname)"
      userprof: "./.bash_profile"
      globprof: "/app/DANTE/.global_profile"
      HOSTNAME: "s01ttapaap"
     # rep_printer: "dhh0297"
     # avb_job_namework: "$(echo AIXJ.PAANWKON|cut -d. -f2-)"
      DD_SYSLST: ">cat >> /app/DANTE/data/rzmeld/${avb_job_namework}.L.`date +%y%m%d`.`date +%H%M%S`.0001569603"
      avb_syslst_path: "$(echo $DD_SYSLST|cut -c9-)"
      DD_LOGFILE: "${avb_syslst_path}.log"
      SHARK_SYS_ACT_CLIENT: "0300"
      ORACLE_BASE: "/app/oracle/product/19.0.0"
      ORACLE_SID: "PA_BMTST"
      ORACLE_HOME: "$ORACLE_BASE/client"
      NLS_LANG: "GERMAN_GERMANY.WE8ISO8859P15"
      NLS_CHARACTERSET: "WE8ISO8859P15"
      NLS_SORT: "BINARY"
      LD_LIBRARY_PATH: "$ORACLE_HOME/lib:${LD_LIBRARY_PATH}"
      CLASSPATH: "$ORACLE_HOME/jlib"
      PATH: "$PATH:$ORACLE_HOME/bin:$ORACLE_HOME/lib:$ORACLE_HOME/OPatch"
      DISPLAY: "localhost:0.0"
      HOMEDB: "PVA"
      "__SESAM_PROPERTY_PATH": "/app/DANTE/exec/conf/0300.sesam.properties.pa2000"
      ESQL_DEBUG: "0"
      MASDAT: "$(date +%Y%m%d)"
      SYS_ORA_LOGIN: "PV/PV@PA_BMTST"
      "DB_LOGIN": "'PALISTVW/t!3FP0stl3rM4rkt@PALISTVW_TEST'"
      LDAPPATH: "/usr"
      LDAP_SERVER: "S01BPVLDAP"
      LDAP_USER: "02autm"
      LDAP_PASSWORT: "mtua20"
      LDAP_DC_PVA: "pva.sozvers.at"
      LDAP_DC_SVA: "sva.sozvers.at"
      LDAP_DC_SVB: "svb.sozvers.at"
      LDAP_DC_VAE: "vaeb.sozvers.at"
      dd_kszlvw: "/app/DANTE/exec/conf/ldap.kszl.verweis.gesamt.txt"
      SHARK_SYS_USER: "pa2000"
      SYS_JV_PATH: "/app/DANTE/work/data/jv/"
      SYS_GLOBAL_JV_FILE: "/app/DANTE/work/data/jv/pa2000.txt"
      SYS_JV_FILE: "pa2000.txt"
      SYS_JK_PATH: "/app/DANTE/work/data/jk/pa2000/"
      SHARK_SYS_ACT_CLIENT: "0300"
      SYS_DRIVE_ORA_LOGIN: "DRIVE_PV/DRIVE_PV@PA_BMTST"
      SYS_DRIVE_HOMEDB: "PVA"
      ORACLE_BASE: "/app/oracle/product/19.0.0"
      ORACLE_SID: "PA_BMTST"
      ORACLE_HOME: "$ORACLE_BASE/client"
      NLS_LANG: "GERMAN_GERMANY.WE8ISO8859P15"
      NLS_CHARACTERSET: "WE8ISO8859P15"
      NLS_SORT: "BINARY"
      LD_LIBRARY_PATH: "$ORACLE_HOME/lib:${LD_LIBRARY_PATH}"
      CLASSPATH: "$ORACLE_HOME/jlib"
      PATH: "$PATH:$ORACLE_HOME/bin:$ORACLE_HOME/lib:$ORACLE_HOME/OPatch"
      DISPLAY: "localhost:0.0"
      SYS_DRIVE_FILE_OUT: "/app/DANTE/data/pa2000"
      SYS_DRIVE_PATH: "/app/DANTE/exec/bin/drive/"
      DANTE_PROPERTIES_FILE: "/app/DANTE/exec/conf/dante.webservice.properties.ttst.ANWTEST"
      ASSENTIS_SERVER: "s01passentisdb:1521:assentis"
      ASSENTIS_USER: "APP_DANTE"
      ASSENTIS_PWD: "danteapp"
      COBDIR: "/opt/microfocus/VisualCOBOL"
      LIBPATH: "$COBDIR/lib"
      PATH: "$PATH:$COBDIR/bin"
      TMPDIR: "/app/cobtmp"
      LANG: "de_DE@euro"
      EXTFH: "/app/DANTE/exec/conf/extfh.cfg"
      SYS_COB_PATH: "/app/DANTE/exec/bin/cob"
      SYS_LIB_PATH: "/app/DANTE/exec/lib"
      SYS_LOG_PATH: "/app/DANTE/data/orclldr"
      #SYS_DATA_PATH_USER: "/app/DANTE/data/$(whoami | sed 's/^bs_//')/"
      SYS_DATA_PATH_USER: "/app/DANTE/data/{{ SHARK_SYS_USER }}/"
      SYS_SCRIPTS_PATH: "/app/DANTE/exec/bin/unix_scripts/"
      PATH: "$PATH:/usr/local/bin"
      PATH: "$PATH:/app/DANTE/exec/bin/c/"
      PATH: "$PATH:/app/DANTE/exec/bin/unix_scripts/"
      PATH: "$PATH:/app/DANTE/exec/bin/cob"
      DD_PASEBEIN: "DAT.PASEB.GRUPPEN.98_if35.jea"
      DD_JKFILE: "${SYS_JK_PATH}JK.PAANWKON"
      DD_JKFILE: "${SYS_JK_PATH}JK.PAANWKON"
      reterr: "$?"
      DD_JKFILE: "${SYS_JK_PATH}JK.PAANWKON"
      NLS_SORT: "BINARY"
      UTMPATH: "/opt/lib/utm70a00/64/"
      MANPATH: ":/opt/puppetlabs/puppet/share/man"
      SYS_CONF_PATH: "/app/DANTE/exec/conf"
      XDG_SESSION_ID: "100449"
      NLS_CHARACTERSET: "WE8ISO8859P15"
      HOSTNAME: "s01ttapaap"
      SHELL: "/bin/bash"
      TERM: "xterm"
      HISTSIZE: "1000"
      TMPDIR: "/app/cobtmp"
      NLS_LANG: "GERMAN_GERMANY.WE8ISO8859P15"
      OLDPWD: "/app/bs_pa2000"
      COBDIR: "/opt/microfocus/VisualCOBOL"
      USER: "bs_pa2000"
      LD_LIBRARY_PATH: "/opt/lib/utm70a00/64//sys:/app/oracle/product/19.0.0/client/lib:/opt/lib/utm70a00/64//sys:/app/oracle/product/19.0.0/client/lib:"
      LD_LIBRARY_PATH_64: "/opt/lib/utm70a00/64//sys:/opt/lib/utm70a00/64//sys:"
      ORACLE_SID: "PA_TTST"
      AZIP: "/usr/bin/zip"
      ORACLE_BASE: "/app/oracle/product/19.0.0"
      EXTFH: "/app/DANTE/exec/conf/extfh.cfg"
      MASDAT: "20210727"
      LIBPATH: "/opt/microfocus/VisualCOBOL/lib"
      MAIL: "/var/spool/mail/bs_pa2000"
      PATH: ".:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/app/oracle/product/19.0.0/client/bin:/app/oracle/product/19.0.0/client/lib:/app/oracle/product/19.0.0/client/OPatch:/opt/microfocus/VisualCOBOL/bin:/usr/bin:/usr/local/bin:/app/DANTE/exec/bin/unix_scripts/:/app/bs_pa2000/.local/bin:/app/bs_pa2000/bin:/app/oracle/product/19.0.0/client/bin:/app/oracle/product/19.0.0/client/lib:/app/oracle/product/19.0.0/client/OPatch:/opt/microfocus/VisualCOBOL/bin:/usr/bin:/usr/local/bin:/app/DANTE/exec/bin/unix_scripts/"
      PWD: "/app/DANTE"
      FULLHOSTNAME: "s01ttapaapcl2"
      LANG: "de_DE@euro"
      EXTSHM: "ON"
      SHLVL: "1"
      HOME: "/app/bs_pa2000"
      LOGNAME: "bs_pa2000"
      CLASSPATH: "/app/oracle/product/19.0.0/client/jlib"
      LESSOPEN: "||/usr/bin/lesspipe.sh %s"
      SERVERS: "0010.4000"
      DISPLAY: "localhost:0.0"
      UTM_LIBS: "/opt/lib/utm70a00/64"
      ORACLE_HOME: "/app/oracle/product/19.0.0/client"
      LOADED_GLOBAL_PROFILE: "true"
      HISTTIMEFORMAT: "%d/%m/%y %T"    
  - debug: msg={{ anwkon.stdout_lines }}
