---
- name: paanwkon_test
  hosts: s01ttapaap
  become: bs_pa2000
  vars:
    data_path: /app/DANTE/data/pa2000
    jk_path: /app/DANTE/work/data/jk/pa2000
    cob_path: /app/DANTE/exec/bin/cob

  tasks:
  - name: clear files
    file:
      path: "{{ data_path }}/temp1"
      state: absent
                                                      
  - name: clear DAT.ANWKONT.DZ
    file:
      path: "{{ data_path }}/DAT.ANWKONT.DZ"
      state: absent

  - name: check if D.FEHLER is present
    file:
      path: "{{ data_path }}/D.FEHLER"
      state: present

  - name: check if D.ANWKONT Files are present
    file:
      path: "{{ data_path }}/DAT.ANWKONT.*"
      state: present

  - name: create jk file and content
    file:
      path: "{{ jk_path }}/JK.PAANWKON"
      state: touch
      content: | 
        OK;;;

  - name: exports for program paanwkon
    shell:
      cmd: "{{ cob_path }}/paanwkon"
    environment:
      DD_ANWKONTB: "{{ data_path }}/DAT.AWNKONT.PAANX200"
      DD_ANWKONTG: "{{ data_path }}/DAT.ANWKONT.PAANX300"
      DD_ANWKONTA: "{{ data_path }}/DAT.AWNKONT.PAANX400"
      DD_ANWPASTL: "{{ data_path }}/PASTLN02.VGLANW.210716.1"
      DD_FEHLER: "{{ data_path }}/D.FEHLER"
      DD_ANWRZDZ: "{{ data_path }}/DAT.ANWKONT.DZ"
      DD_HREZDZ: "{{ data_path }}/DAT.ANWKONT.HREZDZ.xml"
      DD_JKFILE: "{{ jk_path }}/app/DANTE/work/data/jk/pa2000/JK.PAANWKON"
    register: anwkon
  - debug: msg={{ anwkon.stdout }}
  - debug: var=anwkon


   


