---
- name: pafrx999_test
  hosts: s01ttapaap
  strategy: debug
  become_user: bs_pa2000
  become_method: sudo
  vars:
    data_path: /app/DANTE/data/spb
    jk_path: /app/DANTE/work/data/jk/pa2000
    cob_path: /app/DANTE/exec/bin/cob
    

  tasks:
  - name: clear files DAT.PAFRIST.GRUPPEN
    file:
      path: "{{ data_path }}/DAT.PAFRIST.GRUPPEN*"
      state: absent

  - name: clear dat.pafrist.gruppen
    file:
      path: "{{ data_path }}/dat.pafrist.gruppen*"
      state: absent

  - name: clear dat.pafrist.gruppen.line
    file:
      path: "{{ data_path }}/dat.pafrist.gruppen.line"
      state: absent
  - name: create jk file and content
    file:
      path: "{{ jk_path }}/JK.PAFRX999"
      state: touch
      content: | 
        OK;;;
        
  - name: Show userid 
    shell:
        cmd: "whoami"
    register: out
  - debug: msg={{ out.stdout }}      
  
  - name: run cobol program pafrx999
    #command: "echo "{{ tag }} | {{ cob_path }}/pafrx999"
    command: "{{ cob_path }}/pafrx999"
    args:
      stdin: "{{ tag }}"    
    register: pafrx999
    environment: 
      DD_PASEBEIN: "{{ data_path }}/dat.pafrist.gruppen.line"
      NLS_SORT: BINARY
      SYS_CONF_PATH: "/app/DANTE/exec/conf"
      NLS_CHARACTERSET: WE8ISO8859P15
      HOSTNAME: s01ttapaap
      SHELL: /bin/bash
      TERM: xterm
      HISTSIZE: 1000
      TMPDIR: /app/cobtmp
      NLS_LANG: GERMAN_GERMANY.WE8ISO8859P15
      OLDPWD: /app/bs_pa2000
      COBDIR: /opt/microfocus/VisualCOBOL
      USER: bs_pa2000
      LD_LIBRARY_PATH: "/opt/lib/utm70a00/64//sys:/app/oracle/product/19.0.0/client/lib:/opt/lib/utm70a00/64//sys:/app/oracle/product/19.0.0/client/lib:"
      LD_LIBRARY_PATH_64: "/opt/lib/utm70a00/64//sys:/opt/lib/utm70a00/64//sys:"
      ORACLE_SID: PA_TTST
      ORACLE_BASE: /app/oracle/product/19.0.0
      EXTFH: /app/DANTE/exec/conf/extfh.cfg
      LIBPATH: /opt/microfocus/VisualCOBOL/lib
      PATH: ".:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/opt/puppetlabs/bin:/app/oracle/product/19.0.0/client/bin:/app/oracle/product/19.0.0/client/lib:/app/oracle/product/19.0.0/client/OPatch:/opt/microfocus/VisualCOBOL/bin:/usr/bin:/usr/local/bin:/app/DANTE/exec/bin/unix_scripts/:/app/bs_pa2000/.local/bin:/app/bs_pa2000/bin:/app/oracle/product/19.0.0/client/bin:/app/oracle/product/19.0.0/client/lib:/app/oracle/product/19.0.0/client/OPatch:/opt/microfocus/VisualCOBOL/bin:/usr/bin:/usr/local/bin:/app/DANTE/exec/bin/unix_scripts/"
      FULLHOSTNAME: s01ttapaapcl2
      LANG: de_DE@euro
      EXTSHM: "ON"
      HISTCONTROL: ignoredups
      SHLVL: 1
      HOME: /app/bs_pa2000
      LOGNAME: bs_pa2000
      CLASSPATH: /app/oracle/product/19.0.0/client/jlib
      ORACLE_HOME: /app/oracle/product/19.0.0/client
      LOADED_GLOBAL_PROFILE: "true"
      HOMEDB: PVA
      __SESAM_PROPERTY_PATH: /app/DANTE/exec/conf/0002.sesam.properties.pa2000
  - debug:
      msg: "{{ pafrx999 }}"
      verbosity: 4
      
  - name: check if output file exists
    stat:  
      path: "{{ data_path }}/dat.pafrist.gruppen.line"
    register: output1  
  - debug:
      msg: "{{ output1 }}"
      
  - name: check if ISAM File DAT.PAFRIST.GRUPPEN exists
    stat:
      path: "{{ data_path }}/DAT.PAFRIST.GRUPPEN"
    register: output2
  - debug:
      msg: "{{ output2 }}"
        
  - name: rebuild index file with cobol utility
    #command: "rebuild dat.pafrist.gruppen.line,DAT.PAFRIST.GRUPPEN -k:1+2 -r:F35 -o:lseq,ind"
    command: pwd
    args:
      chdir: "{{ data_path }}"
    register: rebuild
  - debug:
      msg: "{{ rebuild }}"
