---
- name: SpbTest1
  hosts: s01ttapaap
  become_user: bs_pa2000
  become_method: sudo
  vars:
    text: "Ausgabe von Job SpbTest1"

  tasks:
    - name: Show Userid
      shell: 
        cmd: "whoami"
      register: out
    - debug: msg={{ out.stdout }}
    - name: show umgebung
      shell:
        cmd: "env"
      register: sout
      environment:
        DD_ANWKONTA: "DAT.ANWKONT.PAANX200"
    - debug: msg={{ sout.stdout }}
      
